### ISSUE TITLE
建议更改totalNum的计算方法

### ISSUE THREAD

**Issue by ch1y0q** [qisumi/SEUGPAHelper#1]
有时只需要计算当前页的成绩。
` let totalNum = parseInt(document.querySelector('.bh-advancedQuery-totalNum').firstChild.innerHTML); ` 直接读取页面上的课程数，忘记把每页显示数量改大容易出现连点几十次计算绩点仍没有反应的情况。
建议改成AllLessons.length

**Comment by qisumi** [comment]
已修复
